version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tp_achat
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring_app:
    image: youssefxammar/tpachatproject:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tp_achat
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure 

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount Prometheus configuration
    ports:
      - "9090:9090"  # Prometheus UI
    depends_on:
      - spring_app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  # Grafana UI
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana  # Persistent storage for Grafana data

volumes:
  grafana_data:
