services:
  # MySQL Database Service
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root    
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    command:
      - "--path.rootfs=/host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    networks:
      - monitoring_network

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
      restart: unless-stopped
      networks:
        - monitoring_network

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      volumes:
        - grafana_data:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin  # Default password (should be changed)
      restart: unless-stopped
      networks:
        - monitoring_network
  
  backend-app:
    image: nyrouz911/devops:latest      
    container_name: backend-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/dbachat?createDatabaseIfNotExist=true&userSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db

volumes:
  mysql-data:
  prometheus_data:
  grafana_data:
  
networks:
  monitoring_network:
  external: true 
