services:
  # MySQL Database Service
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root    
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend-app:
    image: nyrouz911/devops:latest      
    container_name: backend-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/dbachat?createDatabaseIfNotExist=true&userSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db

volumes:
  mysql-data:
