# Utiliser l'image OpenJDK légère
FROM openjdk:11-jre-slim

# Copier l'artefact jar
COPY target/tpAchatProject-1.0.jar app.jar

# Définir le répertoire de travail
WORKDIR /usr/app

# Exposer le port d'écoute de l'application
EXPOSE 8080

# Lancer l'application
CMD ["java", "-jar", "app.jar"]
