# Étape de construction
FROM node:# Step 1: Build
FROM node:16 AS build
WORKDIR /app

# Copy only the package files to cache npm install
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

# Copy the rest of the files and build for production
COPY . .
RUN npm run build --prod

# Step 2: Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/dist/crudtuto-Front /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

